server_config:
    use_dummy: false # set to false to use the real AI model
    default_grade_level: "8"
    default_interest: "General"

# chat_model_config:
#     provider: groq
#     model: llama-3.1-8b-instant
#     kwargs:
#         temperature: 0
chat_model_config:
    provider: google
    model: gemini-2.5-flash-lite
    kwargs:
        temperature: 0

prompts_config:
    system_prompt_file: prompts/meta.txt # prompt based on meta strategy (https://github.com/meta-prompting/meta-prompting?tab=readme-ov-file)
    # system_prompt_file: prompts/simple.txt # simple prompt
    # system_prompt_file: prompts/original.txt # original prompt
